### ISSUE TITLE
About prebuild V8 libraries

### ISSUE THREAD

**Issue by shujunqiao** [ncsoft/Unreal.js-core#11]
Execuse me, Do you push these files to Cloud Disk of google or Cloud disk of BaiDu.
I can't download prebuild V8 libraries, because my ip is in China.
Thanks very mush!

**Comment by nakosung** [comment]
I didn't realize there was a problem to download files from google drive. :) Can you build v8 on your own? https://github.com/ncsoft/Unreal.js/wiki/V8

**Comment by shujunqiao** [comment]
Ok, T'll try it. Thanks!
