### ISSUE TITLE
V8-6.1.534 incomplete

### ISSUE THREAD

**Issue by GeorgeR** [ncsoft/Unreal.js-core#24]
The lib download doesn't include v8_libplatform.lib or v8_nosnapshot.lib

**Comment by crocuis** [comment]
I could not find any problems. I need more explanation.

**Comment by GeorgeR** [comment]
If you download v8-6.1.534-libs.zip, inside that in the Win64 folder, there is no v8_libplatform.lib or v8_nosnapshot.lib, which are required by the plugin.

**Comment by crocuis** [comment]
Delete the lib folder and the v8-6.1.534-lib.zip file in the thirdparty directory and run the script again.
