### ISSUE TITLE
Memory Alignment for FQuat and FTransform

### ISSUE THREAD

**Issue by thejustinwalsh** [ncsoft/Unreal.js-core#27]
I am getting a crash due to Memory Alignment when working with `Quat` types in JS. Looking at the source it appears as if `FQuat` needs to be 16 byte aligned.

For a Quick Fix - Change:
https://github.com/ncsoft/Unreal.js-core/blob/51cf9d2a1d7325dd00be61a1cc803e9a9d76da62/Source/V8/Private/StructMemoryInstance.h#L90-L91

To:
```c++
	// Independent memory buffer
	TArray<uint8, TAlignedHeapAllocator<16>> Buffer;
```

Seems wasteful for structs that do not require alignment, however I am not sure of a better fix.

**Comment by nakosung** [comment]
Thanks for finding out the misalignment. Could you make it as a PR?
