### ISSUE TITLE
MAC UE4.22.3 will stop at 71% when Unreal.js is enabled

### ISSUE THREAD

**Issue by sbfkcel** [ncsoft/Unreal.js-core#45]
![image](https://user-images.githubusercontent.com/5469785/60378241-0ac21c80-9a52-11e9-91b4-d80cd376f77b.png)

**Comment by thejustinwalsh** [comment]
How long did you wait it out? This is common as it compiles shaders around the 70-94% marker upon the first time of opening the project.

You could also attach a debugger and see where the loading is stalled? Could be thread contention as well although seems strange that it would only be an issue specific to mac.

**Comment by sbfkcel** [comment]
For a long time, more than 30 minutes. I can be sure that it is abnormal.

**Comment by acctesttemp** [comment]
I have the same problem, when just copy UnrealJS (linux build) to folder Plugins (not set load by default). 
And I figure out the problem is come from V8 module when remove others for checking loading. But I don't know how to debug for get the extract lines/codes are getting the problem. Hope see some hints or easy way to detect it.

**Comment by nullbus** [comment]
I tried building v8 library with `libcxx_abi_unstable = false` in args.gn (default is true) and it seems working with Mac.

**Comment by kalvinarts** [comment]
@nullbus can you please explain how to do that?

The install script just downloads the pre build binaries and the header files...

I tried to get the v8 source with the depot_tools but can't find the args.gn file that you mentioned.

**Comment by nullbus** [comment]
args.gn file is for each build configuration directory([see](https://www.chromium.org/developers/gn-build-configuration#TOC-Understanding-GN-build-flags)).

You can edit it with editor or using `gn args [build output]`.

But I have problems running script in editor now. I am still investigating about it...

**Comment by kalvinarts** [comment]
Thank you @nullbus 

I'll leave the [docs link on how to compile](https://v8.dev/docs/build-gn), in case someone else want to try to tinker with v8.

**Comment by crocuis** [comment]
Please update https://github.com/ncsoft/unreal.js/wiki/v8.

**Comment by nullbus** [comment]
@crocuis Okay, I've updated wiki about that

**Comment by crocuis** [comment]
https://drive.google.com/open?id=0B0pdCSsHz4YTN2g1cDRuMHhIRzhVdjBycHlyMURIUVBab3pB Is it possible to run this library properly? I've built it with the setting of @nullbus. If this works, I replace the lib files. I was not ready to test its execution in a Mac environment. :(

**Comment by nullbus** [comment]
@crocuis Yes I tested with your binaries and Engine starts well in my Mojave machine

**Comment by thejustinwalsh** [comment]
Latest binaries installed from the shell script are a go for me.

**Comment by thejustinwalsh** [comment]
@sbfkcel It works for you right? Can you close this issue if so. 💯

**Comment by sbfkcel** [comment]
@thejustinwalsh solved. Thank you
