### ISSUE TITLE
Upgrade V8 version to support iOS

### ISSUE THREAD

**Issue by nullbus** [ncsoft/Unreal.js-core#48]
Current V8 version that UnrealJS uses is 7.4.288 but [document says](https://v8.dev/docs/cross-compile-ios) you need 7.5 to build iOS binary.

But upgrading to 7.5 is not enough. This v8 commit below fixes iOS runtime failure.
https://github.com/v8/v8/commit/23d485508b2252f337391b427d658f6f7dc68934

It applied after 7.7.244, so **v8 should be updated at least 7.7.244** to run on iOS well.

I've tested that version but some deprecated function were removed. So I can't compile UnrealJS with newer v8 now. Please check this out.

**Comment by nullbus** [comment]
#40

**Comment by crocuis** [comment]
Since v8 7.7 is not stable, it would be better to cherry-pick the https://github.com/v8/v8/commit/23d485508b2252f337391b427d658f6f7dc68934 commit to the released v8 7.6 branch. What do you think about this?

**Comment by nullbus** [comment]
I would like to cherrypick if it solves the problem now.

**Comment by crocuis** [comment]
updated. https://github.com/ncsoft/Unreal.js-core/commit/c0064d5532418c139bd5afb6664944409f34c000

**Comment by nullbus** [comment]
Thank you for upgrading to 7.7(!). It released few weeks ago.

And other note for building iOS, I met runtime crash with v8 build with `v8_use_snapshot=false`. It seems related to runtime execution memory protection. In [official document](https://v8.dev/docs/cross-compile-ios#manual-build) doesn't mention that option but [Unreal.js wiki](https://github.com/ncsoft/Unreal.js/wiki/V8) does. I think this option should be removed (at least) for IOS if it is not your intention.
