### ISSUE TITLE
Linux v8 libraries malformed (thin)

### ISSUE THREAD

**Issue by thejustinwalsh** [ncsoft/Unreal.js-core#53]
When attempting to build Unreal.js on Linux against the pre-built v8 libraries the linker reports that it can not link due to a malformed archive. Upon further investigation the library files have been produced as thin libraries and without their resulting obj files that they link to are incomplete and malformed.

```sh
head -1 ./ThirdParty/v8/lib/Linux/Release/libv8_libbase.a
!<thin>
```

Without modifying the v8 build files the [method presented here](https://github.com/forwidur/libv8) seems to be the easiest way to modify a build system to produce fat libraries for distribution instead.

```sh
for lib in `find out/x64.release/obj.target/tools/gyp/ -name '*.a'`;
  do ar -t $lib | xargs ar rvs $lib.new && mv -v $lib.new $lib;
done`
```

**Comment by crocuis** [comment]
Merged.

**Comment by thejustinwalsh** [comment]
Are there new binaries available for linux? I do not see any new releases or changes to the v8 repo regarding fat vs thin library support...?

**Comment by crocuis** [comment]
I compiled it as described at https://github.com/ncsoft/Unreal.js/wiki/V8. 
Do you want to compile the links you gave me?

**Comment by thejustinwalsh** [comment]
If you build as described in the wiki link above, you would also need to ship all of the obj files for linux as the libraries produced are thin libraries and simply link to the resulting obj files. So either you need to convert them to fat libraries using the method I initally described, or you need to include the obj files, otherwise you can not link to v8 on linux. As I can not link against libv8_* using Unreal.js at this time.

**Comment by crocuis** [comment]
I understand your opinion. But because the version of v8 we use is different from the version of v8 we use in the link you posted, we need a way to build the fat classes. If you know how to build, post it on https://github.com/ncsoft/Unreal.js/wiki/V8.

**Comment by thejustinwalsh** [comment]
Gotcha. I'll give it a try and build it from source soon and update the wiki if I find a solution.

**Comment by thejustinwalsh** [comment]
Updated Wiki with proper build instructions for Linux.
https://github.com/ncsoft/Unreal.js/wiki/V8

**Comment by thejustinwalsh** [comment]
Rebuilding now to verify... There is a chance that this command still isn't working.

``for lib in `find out/x64.release/obj/ -name '*.a'`; do ar -t $lib | xargs ar rvs $lib.new && mv -v $lib.new $lib; done``

Another option would be to just copy all the folders with the `.o` files along side the `.a` files as the `.a` files simply link directly to the `.o` files by relative path.

**Comment by thejustinwalsh** [comment]
```
[1/7] Link (ld) libUE4Editor-V8.so
/home/justin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: /home/justin/Projects/UnamedJSTool/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp.o: in function `FFrame::FFrame(UObject*, UFunction*, void*, FFrame*, UField*)':
/home/justin/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject/Stack.h:217: undefined reference to `vtable for FFrame'
/home/justin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: /home/justin/Projects/UnamedJSTool/Plugins/UnrealJS/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/V8/Module.V8.cpp.o: in function `~FFrame':
/home/justin/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject/Stack.h:117: undefined reference to `vtable for FFrame'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
The terminal process terminated with exit code: 5
```

Has anyone actually compiled and ran this thing on linux?

**Comment by thejustinwalsh** [comment]
Appears it may be an issue with 4.24 specifically, tracking down now.

**Comment by thejustinwalsh** [comment]
Wiki update correct. Would you mind updating pre-built binaries using the technique described in the wiki.

Also on 4.24 Linux specifically you need to either edit Stack.h like so `struct COREUOBJECT_VTABLE FFrame : public FOutputDevice` or modify the `Engine/Source/Program/UnrealBuildTool/Platforms/LinuxToolchain.cs` with the following code to get UnrealJS to compile...

```
if (CompileEnvironment.bHideSymbolsByDefault)
{
    Result += " -fvisibility-ms-compat";
    Result += " -fvisibility-inlines-hidden";
}
```

This change will not be needed in 4.25

**Comment by thejustinwalsh** [comment]
Appears Linux needs the same fix described in https://github.com/ncsoft/Unreal.js-core/issues/45 regarding the `libcxx_abi_unstable=false` param. Updated Wiki.

**Comment by crocuis** [comment]
updated linux v8 libraries :)

**Comment by crocuis** [comment]
https://github.com/EpicGames/UnrealEngine/commit/e330479d7332c0e6347a54804cbc15b907f79d60 According to this commit, Symbols are now hidden by default. To use Unreal.js on Linux / Mac, it seems simplest to set bPublicSymbolsByDefault to true in BuildConfiguration.

**Comment by m1steranderson** [comment]
On my MAC Late 2015 27 inch not working, sad, cry, pain

**Comment by thejustinwalsh** [comment]
> [EpicGames/UnrealEngine@e330479](https://github.com/EpicGames/UnrealEngine/commit/e330479d7332c0e6347a54804cbc15b907f79d60) According to this commit, Symbols are now hidden by default. To use Unreal.js on Linux / Mac, it seems simplest to set bPublicSymbolsByDefault to true in BuildConfiguration.

I have yet to try this. On one project I was able to compile the plugin, however and a second project I got a bunch of include path and missing definition errors. Will give this approach a try shortly. I still think something may be wrong with the settings for PCH though.

**Comment by thejustinwalsh** [comment]
If i place the following xml into `Engine/Saved/UnrealBuildTool/BuildConfiguration.xml` I am able to get all of my projects to compile on Linux.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
  <BuildConfiguration>
    <bPublicSymbolsByDefault>true</bPublicSymbolsByDefault>
    <bUseAdaptiveUnityBuild>false</bUseAdaptiveUnityBuild>
  </BuildConfiguration>
</Configuration>
```
