### ISSUE TITLE
4.26 wont compile using Linux

### ISSUE THREAD

**Issue by antoine-pous** [ncsoft/Unreal.js-core#68]
Hi,

since a week i'm trying to make your plugin works for my project and each time i'm getting this window:
![Missing TesticulePendu Modules_056](https://user-images.githubusercontent.com/7486600/104483552-8948c580-55c8-11eb-81c3-fb14db4835cb.png)

When i'm clicking on `yes` it ends with
![Error_057](https://user-images.githubusercontent.com/7486600/104483642-a5e4fd80-55c8-11eb-97d2-b1382586808d.png)

I've tried to clone the repository and used the plugin provided on the market place, each time it's exactly the same thing, the plugin wont let UE editor starts.

If i'm applying #53 config the error changes but the editor still wont open the project
![Missing Modules_058](https://user-images.githubusercontent.com/7486600/104487537-86040880-55cd-11eb-93b5-36540a4feb37.png)

I literally spent 5 days to try to figure out what's happening exactly and haven't found any solution. Any help to fix definitely this issue would be really appreciated.

**Config:**
- UE 4.26.0
- Ubuntu 20.04
- VSCode 1.52.1

**Comment by crocuis** [comment]
Fixed. https://github.com/ncsoft/Unreal.js-core/commit/7dc4f660f40a3bc7e74111d627f921032f6547ab

**Comment by antoine-pous** [comment]
Perfect, thank you! :+1:
