### ISSUE TITLE
UE5 build

### ISSUE THREAD

**Issue by drfbwilliams** [ncsoft/Unreal.js-core#80]
Hi there,

Any plans or instructions on how to recompile this awesome project for UE5?

I read through a few of the previous issues and although I understand the code references etc, I'm new to UE plugin development - any pointers would be much appreciated.

Cheers

**Comment by crocuis** [comment]
Check out the v8_9.7 branch.

**Comment by drfbwilliams** [comment]
@crocuis - thanks so much for the response and the direction. Much appreciated.
