### ISSUE TITLE
UE5 Shipping build broken

### ISSUE THREAD

**Issue by SBRK** [ncsoft/Unreal.js-core#82]
The plugin works well in the Editor, but as soon as I want to package a shipping build, some errors related to `ClassGeneratedBy` emerge.

**Comment by hiperbou** [comment]
I'm having the same issue.

Probably related, trying to compile my project using "DebugGame Editor" and "Development Editor" works, buf fails using "Debug Game", "Development" and "Shipping" configurations.

 error C2039: ‘ClassGeneratedBy’: is not a member of ‘UClass’

This variable is under WITH_EDITORONLY_DATA macro in Unreal Engine 5 but earlier it was not.

**Comment by crocuis** [comment]
Fixed. https://github.com/ncsoft/Unreal.js-core/commit/1be08a175116fc021631e12d9f4bbe520482c739
